RSS_URL_PREFIX: https://pub-2ed1c81f567a462ebf4bddb12fb5ad6c.r2.dev/
NEWEST_VIDES_FIRST: false
FETCH_RECENT_N_VIDEOS: 0
channel:
  - uid: 391930545
    sid: 598034
  - uid: 1571561781
    sid: 2586487

# upload oss config
R2:
  ACCESS_KEY: ''
  SECRET_KEY: ''
  ENDPOINT_URL: ''