"""Tests for bilibili_podcast.bilibili.credential."""
from __future__ import annotations

from pathlib import Path

from bilibili_podcast.bilibili import credential as cred_mod
from bilibili_podcast.bilibili.credential import (
    cookie_text,
    load_credential,
    materialize_cookie_file,
    parse_cookie_text,
)


NETSCAPE = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.bilibili.com\tTRUE\t/\tFALSE\t1819936923\tbuvid_fp_plain\tundefined
#HttpOnly_.bilibili.com\tTRUE\t/\tFALSE\t1793579983\tSESSDATA\tsess-value
.bilibili.com\tTRUE\t/\tFALSE\t1793579983\tbili_jct\tjct-value
.bilibili.com\tTRUE\t/\tFALSE\t1793579983\tDedeUserID\t12345
"""


def test_parse_cookie_text_handles_httponly_and_comments():
    cookies = parse_cookie_text(NETSCAPE)
    assert cookies["SESSDATA"] == "sess-value"
    assert cookies["bili_jct"] == "jct-value"
    assert cookies["DedeUserID"] == "12345"
    assert cookies["buvid_fp_plain"] == "undefined"


def test_parse_cookie_text_accepts_whitespace_separated_fields():
    line = ".bilibili.com TRUE / FALSE 0 buvid3 b3-value\n"
    assert parse_cookie_text(line) == {"buvid3": "b3-value"}


def test_parse_cookie_text_ignores_malformed_lines():
    assert parse_cookie_text("garbage\n\n.bilibili.com\tTRUE\n") == {}


def test_cookie_text_prefers_env(monkeypatch, tmp_path: Path):
    (tmp_path / "cookie").write_text("from-file", encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv(cred_mod.COOKIE_ENV_VAR, "from-env")
    assert cookie_text() == "from-env"


def test_cookie_text_falls_back_to_file(monkeypatch, tmp_path: Path):
    (tmp_path / "cookie").write_text(NETSCAPE, encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv(cred_mod.COOKIE_ENV_VAR, raising=False)
    assert cookie_text() == NETSCAPE


def test_cookie_text_returns_none_when_absent(monkeypatch, tmp_path: Path):
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv(cred_mod.COOKIE_ENV_VAR, raising=False)
    assert cookie_text() is None


def test_load_credential_returns_none_without_cookie(monkeypatch, tmp_path: Path):
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv(cred_mod.COOKIE_ENV_VAR, raising=False)
    assert load_credential() is None


def test_load_credential_maps_netscape_fields(monkeypatch):
    monkeypatch.setenv(cred_mod.COOKIE_ENV_VAR, NETSCAPE)
    cred = load_credential()
    assert cred is not None
    assert cred.sessdata == "sess-value"
    assert cred.bili_jct == "jct-value"
    assert cred.dedeuserid == "12345"


def test_materialize_cookie_file_returns_none_without_cookie(monkeypatch, tmp_path: Path):
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv(cred_mod.COOKIE_ENV_VAR, raising=False)
    assert materialize_cookie_file() == (None, False)


def test_materialize_cookie_file_writes_temp_from_env(monkeypatch):
    monkeypatch.setenv(cred_mod.COOKIE_ENV_VAR, NETSCAPE)
    path, is_temp = materialize_cookie_file()
    try:
        assert is_temp is True
        assert Path(path).read_text(encoding="utf-8") == NETSCAPE
    finally:
        Path(path).unlink(missing_ok=True)


def test_materialize_cookie_file_protects_source_cookie(monkeypatch, tmp_path: Path):
    """yt-dlp dumps its jar back into `cookiefile`; the source must survive."""
    source = tmp_path / "cookie"
    source.write_text(NETSCAPE, encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv(cred_mod.COOKIE_ENV_VAR, raising=False)

    path, is_temp = materialize_cookie_file()
    try:
        assert is_temp is True
        assert Path(path) != source
        assert Path(path).read_text(encoding="utf-8") == NETSCAPE
        # simulate yt-dlp rewriting the file it was handed
        Path(path).write_text("clobbered", encoding="utf-8")
        assert source.read_text(encoding="utf-8") == NETSCAPE
    finally:
        Path(path).unlink(missing_ok=True)


def test_load_credential_returns_none_when_only_unrelated_cookies(monkeypatch):
    monkeypatch.setenv(
        cred_mod.COOKIE_ENV_VAR,
        "# Netscape HTTP Cookie File\n"
        "www.bilibili.com\tFALSE\t/\tFALSE\t1789541967\tX-BILI-SEC-TOKEN\tabc\n",
    )
    assert load_credential() is None
