"""b2p-gen-index: generate docs/index.html from config sources."""
from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from bilibili_api.channel_series import ChannelSeries, ChannelSeriesType

from bilibili_podcast.config_loader import load_active_config
from bilibili_podcast.logger import get_logger

logger = get_logger()

_RSS_BEAUTY = "https://rss.beauty/rss?url="


def _html(prefix: str, entries: list[tuple[str, str, str, str]]) -> str:
    items = "\n".join(
        f'<a href="{_RSS_BEAUTY}{prefix}/rss/{kind}/{sid}.xml">{title}</a>'
        for kind, sid, uid, title in entries
    )
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>bilibili podcast</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 680px; margin: 40px auto; padding: 0 20px; color: #333; }}
  h1 {{ font-size: 1.8em; margin-bottom: 4px; }}
  a {{ display: block; padding: 10px 0; border-bottom: 1px solid #eee; color: #0066cc; text-decoration: none; font-size: 1.05em; }}
  a:hover {{ color: #004499; }}
  .footer {{ margin-top: 40px; font-size: 0.85em; color: #aaa; }}
</style>
</head>
<body>
<h1>bilibili podcast</h1>
{items}
<div class="footer">Generated by b2p-gen-index</div>
</body>
</html>
"""


def _fetch_title(sid: str, uid: str, kind: str) -> str:
    stype = ChannelSeriesType.SEASON if kind == "season" else ChannelSeriesType.SERIES
    cs = ChannelSeries(id_=sid, uid=uid, type_=stype)
    meta = asyncio.run(cs.get_meta())
    if kind == "season":
        return meta.get("title") or meta.get("upper", {}).get("name") or f"合集 {sid}"
    return meta.get("name") or f"系列 {sid}"


def generate(config_path: str, output: str) -> None:
    config = load_active_config(config_path)
    prefix = config["RSS_URL_PREFIX"].rstrip("/")

    entries: list[tuple[str, str, str, str]] = []
    for c in config["season"]:
        sid, uid = str(c["sid"]), str(c["uid"])
        title = _fetch_title(sid, uid, "season")
        entries.append(("season", sid, uid, title))
    for c in config["series"]:
        sid, uid = str(c["sid"]), str(c["uid"])
        title = _fetch_title(sid, uid, "series")
        entries.append(("series", sid, uid, title))

    Path(output).write_text(_html(prefix, entries), encoding="utf-8")
    logger.info(f"===> wrote {output} ({len(entries)} entries)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/index.html from config")
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--output", default="docs/index.html")
    args = parser.parse_args(argv)
    generate(args.config, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
