name: Build and Deploy

on:
  push:
    tags:
      - "*"

# Environment variables available to all jobs and steps in this workflow.
env:
  IMAGE: bilibili-podcast
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      run: |
        docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:$TAG" .
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:$TAG"
